# import = ["/home/merak/.config/alacritty/themes/rose-pine-moon.toml"]
general.live_config_reload = true
general.import = ["/home/merak/.config/alacritty/themes/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
dimensions = { columns = 150, lines = 40 }
padding = { x = 2, y = 1 }

[scrolling]
history = 5000
multiplier = 3

[cursor]
blink_interval = 500
style = { shape = "Block", blinking = "On" }

[font]
size = 20
# normal = { family = "Maple Mono NL NF CN", style = "Normal" }
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold = { family = "Maple Mono NL NF CN", style = "Bold" }
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "Operator Mono Bold", style = "Bold Italic" }
bold_italic = { family = "Operator Mono Bold", style = "Bold Italic" }


[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "Paste" }]

[keyboard]
bindings = [
  { key = "P", mods = "Alt", action = "Paste" },
  { key = "Space", mods = "Alt", mode = "~Search", action = "ToggleViMode" },
  { key = "Copy", mods = "None", action = "Copy" },
  { key = "Paste", mods = "None", action = "Paste" },
]

[terminal]
